openapi: 3.0.3
info:
  title: API de Videojuego - Jugadores y Progreso
  version: 1.0.0
  description: API REST para gestionar jugadores, autenticación, progreso y solicitudes de amistad en un videojuego.

servers:
  - url: https://desarrollar-api-documentada.onrender.com/apiV1
    description: Servidor principal

tags:
  - name: Usuarios
  - name: Jugadores
  - name: Progreso
  - name: Solicitudes

paths:
  /usuarios/registro:
    post:
      tags: [Usuarios]
      summary: Registrar nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required: [nombre, email, password]
      responses:
        "200":
          description: Usuario registrado

  /usuarios/login:
    post:
      tags: [Usuarios]
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        "200":
          description: Login exitoso

  /players:
    get:
      tags: [Jugadores]
      summary: Obtener todos los jugadores
      responses:
        "200":
          description: Lista de jugadores

  /progreso/{id}:
    get:
      tags: [Progreso]
      summary: Obtener progreso de un jugador
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Datos de progreso

  /progreso/{id}:
    patch:
      tags: [Progreso]
      summary: Actualizar progreso del jugador
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                experiencia:
                  type: integer
                nivel:
                  type: integer
                logros:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Progreso actualizado

  /usuarios/solicitud:
    get:
      tags: [Solicitudes]
      summary: Obtener todas las solicitudes de amistad
      responses:
        "200":
          description: Lista de solicitudes

    post:
      tags: [Solicitudes]
      summary: Enviar solicitud de amistad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                de_usuario_id:
                  type: string
                para_usuario_id:
                  type: string
              required: [de_usuario_id, para_usuario_id]
      responses:
        "200":
          description: Solicitud creada

  /usuarios/solicitud/{id}:
    get:
      tags: [Solicitudes]
      summary: Obtener detalles de una solicitud
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detalles de la solicitud

    patch:
      tags: [Solicitudes]
      summary: Aceptar o rechazar solicitud
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                estado:
                  type: string
                  enum: [aceptada, rechazada]
              required: [estado]
      responses:
        "200":
          description: Solicitud actualizada

    delete:
      tags: [Solicitudes]
      summary: Eliminar solicitud de amistad
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Solicitud eliminada

  /usuarios/solicitud/usuario/{id}:
    get:
      tags: [Solicitudes]
      summary: Obtener solicitudes para un usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Lista de solicitudes para el usuario

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
