openapi: 3.0.3
info:
  title: API de Videojuego - Jugadores y Progreso
  version: 1.0.0
  description: API REST para gestionar jugadores, autenticación, progreso y solicitudes de amistad en un videojuego.

servers:
  - url: https://desarrollar-api-documentada.onrender.com/apiV1
    description: Servidor principal

tags:
  - name: Usuarios
  - name: Jugadores
  - name: Progreso
  - name: Solicitudes

paths:
  /usuarios/register:
    post:
      summary: Registrar un nuevo jugador
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioRegistro'
      responses:
        '201':
          description: Usuario registrado con éxito

  /usuarios/login:
    post:
      summary: Autenticación y obtención de token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticación exitosa

  /usuarios/{id}:
    get:
      summary: Obtener datos de un usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos del usuario
    put:
      summary: Actualizar información del jugador
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioUpdate'
      responses:
        '200':
          description: Usuario actualizado
    patch:
      summary: Actualizar información del jugador parcialmente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Usuario actualizado parcialmente
    delete:
      summary: Eliminar un usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario eliminado

  /usuarios/{id}/progreso:
    get:
      summary: Obtener el progreso del jugador
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Progreso del jugador
    put:
      summary: Actualizar nivel y experiencia
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProgresoUpdate'
      responses:
        '200':
          description: Progreso actualizado

  /usuarios/{id}/subirNivel:
    post:
      summary: Sube el nivel del jugador
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Nivel subido

  /usuarios/solicitud:
    post:
      summary: Registrar una solicitud de amistad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolicitudAmistad'
      responses:
        '200':
          description: Solicitud registrada

  /usuarios/solicitud/{id}:
    get:
      summary: Obtener datos de una solicitud o lista de solicitudes de un usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos de la solicitud o solicitudes del usuario
    patch:
      summary: Actualizar el estado de una solicitud
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                estado:
                  type: string
                  enum: [aceptada, rechazada]
      responses:
        '200':
          description: Estado de solicitud actualizado
    delete:
      summary: Eliminar Solicitud
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Solicitud eliminada

components:
  schemas:
    UsuarioRegistro:
      type: object
      required:
        - nombre
        - email
        - password
      properties:
        nombre:
          type: string
        email:
          type: string
        password:
          type: string

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    UsuarioUpdate:
      type: object
      properties:
        nombre:
          type: string
        email:
          type: string

    ProgresoUpdate:
      type: object
      properties:
        nivel:
          type: integer
        experiencia:
          type: integer

    SolicitudAmistad:
      type: object
      required:
        - de_usuario_id
        - para_usuario_id
      properties:
        de_usuario_id:
          type: string
        para_usuario_id:
          type: string
